name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x
      - run: deno fmt --check
      - run: deno lint
      - name: test
        run: |
          deno test \
            --allow-read --allow-write --allow-env --allow-net --no-check \
            aws-context-guard/tests/ \
            aws-rds-inventory/tests/ \
            aws-rds-inventory-csv/tests/ \
            aws-s3-bucket-audit/tests/
